root: true
env:
  node: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2020
plugins:
  - import
  - '@typescript-eslint'
rules:
  import/default: off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/explicit-function-return-type': off
settings:
  import/resolver:
    typescript: {}
