version: '3.7'

services:
  web:
    build:
      context: ./rails
      dockerfile: ../build/rails/Dockerfile.dev
      target: rails
    command: bundle exec spring server
    depends_on:
      - db
      - webpack
    stdin_open: true
    tty: true
    tmpfs:
      - /app/tmp/pids
    volumes:
      - ./rails:/app:cached
  webpack:
    build:
      context: ./webpack
      dockerfile: ../build/webpack/Dockerfile.dev
      target: webpack
    volumes:
      - ./rails/public/packs:/app/rails/public/packs:cached
      - ./webpack:/app/webpack:cached
      - /app/webpack/node_modules
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local
