env:
  es2020: true
  jest: true
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/explicit-function-return-type': off
