name: Run ESLint

on:
  pull_request:
    paths:
      - webpack/**/*.tsx?
      - webpack/**/*.vue
  push:
    branches:
      - master
      - develop

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webpack
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Fetch yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Fetch yarn cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Run yarn install
        run: yarn install --frozen-lockfile
      - name: Run yarn eslint
        run: yarn eslint
